// <auto-generated />
using System;
using DDAC_System.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DDAC_System.Migrations.System_ClassDB
{
    [DbContext(typeof(System_ClassDBContext))]
    [Migration("20230902170457_NewAssignmentModel")]
    partial class NewAssignmentModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DDAC_System.Models.AcademicClass", b =>
                {
                    b.Property<int>("Class_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ClassEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ClassStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Class_Lecturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Class_Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Class_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Class_ID");

                    b.ToTable("AcademicClass");
                });

            modelBuilder.Entity("DDAC_System.Models.Assignment", b =>
                {
                    b.Property<int>("AssignmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AssignmentDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AssignmentDue")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AssignmentHandOut")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Class_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AssignmentID");

                    b.HasIndex("Class_Name");

                    b.ToTable("Assignment");
                });

            modelBuilder.Entity("DDAC_System.Models.Assignment", b =>
                {
                    b.HasOne("DDAC_System.Models.AcademicClass", "AcademicClass")
                        .WithMany("Assignment")
                        .HasForeignKey("Class_Name")
                        .HasPrincipalKey("Class_Name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
